// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xmucxSWALjVvlXEevtyv2-DvVN56H6Q',
    appId: '1:231990476694:android:bd42397867c792a43167b7',
    messagingSenderId: '231990476694',
    projectId: 'livo-app-firebase',
    databaseURL: 'https://livo-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'livo-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Mg1-M3U3ODeuig42AljhWyDGr6hWt6k',
    appId: '1:231990476694:ios:e4b4a0dac45194433167b7',
    messagingSenderId: '231990476694',
    projectId: 'livo-app-firebase',
    databaseURL: 'https://livo-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'livo-app-firebase.appspot.com',
    iosClientId: '231990476694-h4b3linsami9lbn6pvqndcho3fvblp2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.livoApp',
  );
}
