name: livo_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  result_dart: ^1.1.0
  widget_and_text_animator: ^1.1.5
  google_fonts: ^6.2.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  flutter_modular: ^6.3.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
  #   - images/a_dot_ham.jpeg

